#!/bin/bash
#$ -S /bin/bash
#$ -N bcf_cat
#$ -cwd
#$ -o /mnt/analysis-psp/users/timchang/v3/pc/2211/data/vcfs/bm/$TASK_ID.log
#$ -j y
#$ -m bea
#$ -l h_data=8G,h_rt=48:00:00
#$ -hold_jid normann
#$ -t 1:22


##===keeps biallelic within our dataset that are multiallelic
##concat by chr
##sort 
##remove exact duplicates (position, ref, alt). keeps the first one. could have ben generated by left align split multiallelic wit other split multiallelic or with biallelic. https://github.com/samtools/bcftools/issues/1585
## fill-tags for AC/AN
## remove monomorphic

chr=($(seq 1 1 22) X Y M)

echo ${chr[${SGE_TASK_ID}-1]}

indirb=/mnt/analysis-psp/users/timchang/v3/pc/2211/data/vcfs/bi/norm/
infileheadb=r3.bi.chr
infiletailb=.PspNhwCon.QC.f1.vcf.gz
infileb=${indirb}${infileheadb}${chr[${SGE_TASK_ID}-1]}${infiletailb} 

indirmb=/mnt/analysis-psp/users/timchang/v3/pc/2211/data/vcfs/multi/norm/
infileheadmb=r3.multi.chr
infiletailmb=.PspNhwCon.f1.vcf.gz
infilemb=${indirmb}${infileheadmb}${chr[${SGE_TASK_ID}-1]}${infiletailmb} 


outdir=/mnt/analysis-psp/users/timchang/v3/pc/2211/data/vcfs/bm/
outfilehead=r3.bm.chr
outfiletail=.PspNhwCon.vcf.gz
outfile=${outdir}${outfilehead}${chr[${SGE_TASK_ID}-1]}${outfiletail}

tempdir=${outdir}${chr[${SGE_TASK_ID}-1]}
rm -r $tempdir
mkdir $tempdir

echo $infileb
echo $infilemb
ulimit -n 5000

bcftools concat -Ou $infileb $infilemb | bcftools sort -Ou -T $tempdir | bcftools norm -d exact -Ou | bcftools +fill-tags -Ou -- -t AC,AN,AF,MAF,NS | bcftools filter -e 'AC==0 || AC==AN' -Oz -o $outfile ;

tabix -p vcf $outfile;
bcftools index -n $infileb;
bcftools index -n $infilemb;
bcftools index -n $outfile;

